language: cpp
sudo: required
dist: bionic
addons:
  coverity_scan:
    project:
      name: LandOfTheRair/core2
      description: Back-end for land of the rair
    notification_email: kingoipo@gmail.com
    build_command_prepend: cmake
    build_command: make
    branch_pattern: coverity_scan
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        update: true
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - gcc-9
          - g++-9
          - cmake
          - binutils
    env:
      - MAKEFLAGS=-j2
    script:
      - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
      - gcc -v && g++ -v && cmake --version
      - ./compile_external_release.sh
      - cmake -DCMAKE_BUILD_TYPE=Release .
      - make
