language: cpp
sudo: required
dist: bionic
addons:
  coverity_scan:
    project:
      name: LandOfTheRair/core2
      description: Back-end for land of the rair
    notification_email: kingoipo@gmail.com
    build_command_prepend: cmake
    build_command: make
    branch_pattern: coverity_scan
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        update: true
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - gcc-9
          - g++-9
          - cmake
          - binutils
    env:
      - MAKEFLAGS=-j2
      - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    before_script:
      - eval "${MATRIX_EVAL}"
    script:
      - gcc -v && g++ -v && cmake --version
      - ./compile_external_release.sh
      - cmake -DCMAKE_BUILD_TYPE=Release .
      - make
    after_script:
      - eval "$(ssh-agent -s)"
      - echo "$SSH_KEY" | base64 -d > test.zip
      - unzip test.zip
      - export TEMPFILE=$(mktemp)
      - echo "$SSH_KNOWN_HOSTS" > $TEMPFILE
      - scp -o "UserKnownHostsFile $TEMPFILE" -i deploy_rsa bin/lotr_backend lotr@${DEPLOY_SERVER}:/home/lotr/lotr_backend
      - ssh -o "UserKnownHostsFile $TEMPFILE" -i deploy_rsa lotr@${DEPLOY_SERVER} 'tmux new-session -d -s "myTempSession" /home/lotr/restart_lotr.sh'
